variables:
  buildNumber: $[ counter('constant', 13000) ] # Start higher than our AppVeyor versions. Every build (pr or branch) will increment.

name: 2.0.$(buildNumber)
  
pr:
  branches:
    include:
    - yojagad/CheckDownload2

trigger:
  branches:
    include:
    - yojagad/CheckDownload2

- job: BuildArtifacts_Windows
  variables:
    suffix: '-ci'
  pool:
    vmImage: 'vs2017-win2016' 
  steps:
  - template: build/pipelines/usedotnet.yml
  - task: PowerShell@2
    displayName: "Build artifacts"
    inputs:
      filePath: '$(Build.Repository.LocalPath)\build.ps1'
      arguments: '-buildNumber "$(buildNumber)" -suffix "$(suffix)"'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\buildoutput'
      Contents: 'WebJobs.Script.Performance.App*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\Performance'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\buildoutput'
      Contents: '*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)\buildoutput'
      Contents: '*.zip'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - publish: $(Build.ArtifactStagingDirectory)\Functions.2.0.$(buildNumber)$(suffix).no-runtime.zip
    artifact: Functions.2.0.$(buildNumber)$(suffix).no-runtime
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Binaries.2.0.$(buildNumber)$(suffix).no-runtime.zip
    artifact: Functions.Binaries.2.0.$(buildNumber)$(suffix).no-runtime
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Private.2.0.$(buildNumber)$(suffix).no-runtime.zip
    artifact: Functions.Private.2.0.$(buildNumber)$(suffix).no-runtime
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Private.2.0.$(buildNumber)$(suffix).win-x32.inproc.zip
    artifact: Functions.Private.2.0.$(buildNumber)$(suffix).win-x32.inproc
  - publish: $(Build.ArtifactStagingDirectory)\Functions.2.0.$(buildNumber)$(suffix).zip
    artifact: Functions.2.0.$(buildNumber)$(suffix)
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Binaries.2.0.$(buildNumber)$(suffix).zip
    artifact: Functions.Binaries.2.0.$(buildNumber)$(suffix)
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Symbols.2.0.$(buildNumber)$(suffix).win-x64.zip
    artifact: Functions.Symbols.2.0.$(buildNumber)$(suffix).win-x64
  - publish: $(Build.ArtifactStagingDirectory)\Functions.Symbols.2.0.$(buildNumber)$(suffix).win-x86.zip
    artifact: Functions.Symbols.2.0.$(buildNumber)$(suffix).win-x86
  - publish: $(Build.ArtifactStagingDirectory)\Microsoft.Azure.WebJobs.Script.2.0.$(buildNumber)$(suffix).nupkg
    artifact: Microsoft.Azure.WebJobs.Script.2.0.$(buildNumber)$(suffix)
  - publish: $(Build.ArtifactStagingDirectory)\Microsoft.Azure.WebJobs.Script.Grpc.2.0.$(buildNumber)$(suffix).nupkg
    artifact: Microsoft.Azure.WebJobs.Script.Grpc.2.0.$(buildNumber)$(suffix)
  - publish: $(Build.ArtifactStagingDirectory)\Microsoft.Azure.WebJobs.Script.WebHost.2.0.$(buildNumber)$(suffix).nupkg
    artifact: Microsoft.Azure.WebJobs.Script.WebHost.2.0.$(buildNumber)$(suffix)
    condition: succeeded()
  - publish: $(Build.ArtifactStagingDirectory)\Performance
    artifact: WebJobs.Script.Performance.App$(suffix)
    condition: succeeded()